eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
  http2:
    enabled: true
spring:
  application:
    name: service-feign
#  zipkin:
#    base-ur: http://localhost:9411
  http:
    multipart:
      max-file-size: 10000000MB
      max-request-size: 10000000MB