
spring:
  application:
    name: service-authrization
  datasource:
    url: jdbc:mysql://192.168.0.21:3306/user_center?characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    username: developer
    password: uX%CU9CS
    hikari:
      max-lifetime: 1765000
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.241:8761/eureka/
