eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.241:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: service-ribbon
  zipkin:
    base-ur: http://localhost:9411
