eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.241:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: service-miya
  zipkin:
    base-ur: http://192.168.0.241:9411
server:
  port: 8989

