eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.241:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8762
spring:
  application:
    name: service-hi
  zipkin:
      base-ur: http://localhost:9411